// getting output in js 
// console.log("Hello World")
// console.log(10)
// console.log("Hellow World",10)
// console.log("Devarsh"+" "+"Dubey")
// console.log("Devarsh","Dubey")
// console.log(10,20)
// console.log(10+20)
console.log("10","20")
console.log("10"+20)
console.log(typeof("devarsh"))
console.log(typeof(52))
console.log(typeof(1.25))
console.log(typeof(12.25))
console.log(typeof(true))
console.log("Hello Uncle Namaste")
console.log("Khana khaya kya")
console.log("Hello Uncle Namaste \n Khana khaya kya \n Kha lo varna Dyan leke jayegi")
 